# Generated by Django 3.1.2 on 2020-10-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paid', models.CharField(default='N', max_length=1)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='R', max_length=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tickets', related_query_name='Ticket', to='tickets.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tickets', related_query_name='Ticket', to='tickets.tickettype')),
            ],
        ),
    ]
