# Generated by Django 3.1.2 on 2020-10-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_auto_20201026_1420"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ticket",
            new_name="TicketType",
        ),
    ]
